config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: {
      registrations: 'users/registrations',
      sessions: 'users/sessions',
      passwords: 'users/passwords'
    }
  post 'downgrade', to: 'users#downgrade', as: 'downgrade'

  resources :charges, only: [:new, :create]
  get 'receipt', to: 'charges#receipt', as: 'receipt'

  resources :wikis
  root 'welcome#index'

end

app/models/wiki.rb
# == Schema Information
#
# Table name: wikis
#
#  id         :integer          not null, primary key
#  title      :string           default(""), not null
#  body       :text             default("")
#  private    :boolean          default(FALSE), not null
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_wikis_on_user_id  (user_id)
#

class Wiki < ActiveRecord::Base
  belongs_to :user

  scope :public_wikis, -> { where(private: false) }
  scope :visible_to, -> (user) { user ? Wiki.where(user_id: user.id) : public_wikis}

end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  before_action :set_wiki, only: [:show, :edit, :update, :destroy]
  before_action :validate_ownership, only: [:show, :edit, :update, :destroy]

  # GET /wikis
  # GET /wikis.json
  def index
    @wikis = Wiki.visible_to(current_user)
  end

  # GET /wikis/1
  # GET /wikis/1.json
  def show
  end

  # GET /wikis/new
  def new
    @wiki = current_user.wikis.new
  end

  # GET /wikis/1/edit
  def edit
  end

  # POST /wikis
  # POST /wikis.json
  def create
    @wiki = current_user.wikis.new(wiki_params)
    @wiki.user_id = current_user.id

    respond_to do |format|
      if @wiki.save
        format.html { redirect_to @wiki, notice: 'Wiki was successfully created.' }
        format.json { render :show, status: :created, location: @wiki }
      else
        format.html { render :new }
        format.json { render json: @wiki.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wikis/1
  # PATCH/PUT /wikis/1.json
  def update
    authorize @wiki

    respond_to do |format|
      if @wiki.update(wiki_params)
        format.html { redirect_to @wiki, notice: 'Wiki was successfully updated.' }
        format.json { render :show, status: :ok, location: @wiki }
      else
        format.html { render :edit }
        format.json { render json: @wiki.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wikis/1
  # DELETE /wikis/1.json
  def destroy
    @wiki.destroy
    respond_to do |format|
      format.html { redirect_to wikis_url, notice: 'Wiki was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  #
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wiki
      @wiki = Wiki.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def wiki_params
      params.require(:wiki).permit(:title, :body, :private, :user_id)
    end

    def validate_ownership
      unless !@wiki.private || @wiki.user_id == current_user.id
        flash[:alert] = "You must be signed in to view private topics."
        redirect_to new_user_session_path
      end
    end
end

app/helpers/wikis_helper.rb
module WikisHelper
  def private_wiki_permitted?
    current_user && (current_user.admin? || current_user.premium?)
  end
end

app/views/wikis/_form.html.slim
= form_for @wiki do |f|
  - if @wiki.errors.any?
    #error_explanation
      h2 = "#{pluralize(@wiki.errors.count, "error")} prohibited this wiki from being saved:"
      ul
        - @wiki.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :body
    = f.text_area :body
  - if private_wiki_permitted?
    .field
      = f.label :private
      = f.check_box :private
  .actions = f.submit

app/views/wikis/edit.html.slim
h1 Editing wiki

== render 'form'

= link_to 'Show', @wiki
'  |
= link_to 'Back', wikis_path

app/views/wikis/index.html.slim
h1 Listing wikis

table
  thead
    tr
      th Title
      th Body
      th Private
      th User
      th
      th
      th

  tbody
    - @wikis.each do |wiki|
      tr
        td = markdown(wiki.title)
        td = markdown(wiki.body)
        td = wiki.private
        td = wiki.user.username
        td = link_to 'Show', wiki
        td = link_to 'Edit', edit_wiki_path(wiki)
        td = link_to 'Destroy', wiki, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Wiki', new_wiki_path

app/views/wikis/new.html.slim
h1 New wiki

== render 'form'

= link_to 'Back', wikis_path

app/views/wikis/show.html.slim
p#notice = notice

p
  strong Title:
  = markdown(@wiki.title)
p
  strong Body:
  = markdown(@wiki.body)
p
  strong Private:
  = @wiki.private
p
  strong Author:
  = @wiki.user.username

= link_to 'Edit', edit_wiki_path(@wiki)
'  |
= link_to 'Back', wikis_path